name: PR Agent

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run PR Agent on PR
    steps:
      - name: PR Agent action
        id: pr_agent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }} # 깃허브 시크릿에 설정
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_CODE_SUGGESTIONS.extra_instructions: "한국어로 답변해줘. 사용되지 않는 import 제거, 불필요한 코드 최적화 위주로 피드백해줘."